FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json ./
RUN npm install

# Copy source code
FROM base AS tester
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Run tests
CMD ["npm", "test"]
